export enum OrderStatus {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  PACKED = 'PACKED',
  PAID = 'PAID',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',

  CANCELED = 'CANCELED',
}
